# Generated by Django 4.1.6 on 2023-02-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0002_alter_fileupload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
