# Generated by Django 4.1.6 on 2023-02-03 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0005_alter_fileuploads_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUploads',
        ),
    ]
