# Generated by Django 4.1.6 on 2023-02-03 05:03

import assignment1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0006_delete_fileuploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='uname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to=assignment1.models.userDirectoryPath),
        ),
    ]
