# Generated by Django 4.1.6 on 2023-02-04 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0007_fileupload_uname_alter_fileupload_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='uname',
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])]),
        ),
    ]
